[package]
name = "test_os"
version = "0.1.0"
authors = ["Benjamin Thomas <ben@benthomas.ca>"]
edition = "2018"

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x4", "-serial", "stdio", "-display", "none"]
test-success-exit-code = 1

[package.metadata.bootloader]
kernel-stack-address = "0xFFFFFFF000000000"
kernel-stack-size = 64
physical-memory-offset = "0xFFFFF80000000000"

[dependencies]
bootloader = { version = "0.9.16", features = ["map_physical_memory"] }
itertools = { version = "0.10.0", default-features = false, features = ["use_alloc"] }
spin = "0.7.1"
uart_16550 = "0.2.12"
x86_64 = "0.13.2"
